services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./client
    command: npm run dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'

volumes:
  pgdata:
