services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: learning_tool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
  api:
    build: ./server
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file: server/.env
    depends_on: [db]
    ports: ["8000:8000"]
  web:
    build: ./client
    command: yarn start
    ports: ["3000:3000"]
    depends_on: [api]
