# Generated by Django 5.2.1 on 2025-06-04 15:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body_markdown", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        default=list,
                        size=None,
                    ),
                ),
                ("difficulty", models.CharField(max_length=20)),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("code", "Code Lab"),
                            ("proj", "Project"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ext_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("started", "started"), ("completed", "completed")],
                        max_length=12,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="modules.module"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "module")},
            },
        ),
    ]
