# Generated by Django 5.2.1 on 2025-06-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="body_markdown",
        ),
        migrations.RemoveField(
            model_name="module",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="module",
            name="ext_url",
        ),
        migrations.RemoveField(
            model_name="module",
            name="tags",
        ),
        migrations.AddField(
            model_name="module",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="duration",
            field=models.FloatField(default=0, help_text="Duration in hours"),
        ),
        migrations.AddField(
            model_name="module",
            name="goal_tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="module",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner level"),
                    ("intermediate", "Intermediate level"),
                    ("advanced", "Advanced level"),
                ],
                default="beginner",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="popularity",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="module",
            name="skill_tags",
            field=models.JSONField(default=list),
        ),
    ]
