# Generated by Django 5.2.1 on 2025-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modules",
            "0002_remove_module_body_markdown_remove_module_difficulty_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="level",
            field=models.CharField(default="Beginner level", max_length=12),
        ),
    ]
