# Generated by Django 5.2.1 on 2025-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_alter_module_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="level",
            field=models.CharField(default="Beginner level", max_length=20),
        ),
    ]
