# Generated by Django 5.2.1 on 2025-06-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0004_alter_module_level"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Progress",
        ),
    ]
