name: Docker CI

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all services
        run: docker compose build

      - name: Run backend tests
        run: docker compose run --rm backend pytest

      - name: Run frontend tests
        run: docker compose run --rm frontend yarn test
